### PR TITLE
build in docker build rather than having artefacts in git

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by timgent** [comment]
@chrisns I like the idea but if we do this the Github pages link won't work anymore

**Comment by timgent** [comment]
@chrisns Cool so basically current changes mean that travis will push the built artefacts to a branch just for github pages?

**Comment by chrisns** [comment]
@timgent yeah thats the plan, I need to get access to the ukhomeoffice-bot user again to accept the invite to collaborate on this project. I foolishly threw away the password :)

**Comment by chrisns** [comment]
superseded by #15

**Pull request closed without merging**
